# Generated by Django 6.0 on 2025-12-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('point_load', models.IntegerField(blank=True, null=True)),
                ('load_per_distance', models.IntegerField(blank=True, null=True)),
                ('distance_from_left_end', models.IntegerField()),
            ],
        ),
    ]
