# Generated by Django 6.0 on 2025-12-29 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load',
            old_name='distance_from_left_end',
            new_name='horizontal_distance_from_left_end_origin',
        ),
        migrations.RenameField(
            model_name='load',
            old_name='point_load',
            new_name='left_load_per_distance',
        ),
        migrations.AddField(
            model_name='load',
            name='axis',
            field=models.CharField(default='-y', max_length=10),
        ),
        migrations.AddField(
            model_name='load',
            name='load_span',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='point_load_magnitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='question.question'),
        ),
        migrations.AddField(
            model_name='load',
            name='right_load_per_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='vertical_distance_from_left_end_origin',
            field=models.IntegerField(default=0),
        ),
    ]
