# Generated by Django 6.0 on 2025-12-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Span',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('ei', models.IntegerField(default=1)),
                ('axis', models.CharField(max_length=20)),
                ('fem_left', models.IntegerField(blank=True, null=True)),
                ('fem_right', models.IntegerField(blank=True, null=True)),
                ('moment_left', models.IntegerField(blank=True, null=True)),
                ('moment_right', models.IntegerField(blank=True, null=True)),
                ('moment_left_eqn', models.CharField(blank=True, max_length=200, null=True)),
                ('moment_right_eqn', models.CharField(blank=True, max_length=200, null=True)),
                ('distance_from_left_end', models.IntegerField()),
            ],
        ),
    ]
