# Generated by Django 6.0 on 2025-12-29 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
        ('span', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='span',
            old_name='distance_from_left_end',
            new_name='horizontal_distance_from_left_end_origin',
        ),
        migrations.AddField(
            model_name='span',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='question.question'),
        ),
        migrations.AddField(
            model_name='span',
            name='vertical_distance_from_left_end_origin',
            field=models.IntegerField(default=0),
        ),
    ]
