# Generated by Django 6.0 on 2026-01-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('span', '0002_rename_distance_from_left_end_span_horizontal_distance_from_left_end_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='span',
            name='shear_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='span',
            name='shear_right',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
