# Generated by Django 6.0 on 2025-12-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('horizontal_reaction', models.IntegerField(default=0)),
                ('vertical_reaction', models.IntegerField(blank=True, null=True)),
                ('slope', models.IntegerField(default=0)),
                ('deflection', models.IntegerField(default=0)),
                ('left_half_vertical_reaction', models.IntegerField(blank=True, null=True)),
                ('right_half_vertical_reaction', models.IntegerField(blank=True, null=True)),
                ('distance_from_left_end', models.IntegerField()),
            ],
        ),
    ]
